services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snowflake 
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"